const merge = require('webpack-merge')
const { FRONT } = require('../../PATHS')
const {
  injectStyles,
  loadDevMedia,
  setupDevServer,
  setupHTML,
} = require('../parts')

module.exports = merge([
  {
    entry: `${FRONT.SRC}/front-dev.jsx`,
    output: {
      path: FRONT.BUILD_FRONT_DEV,
    },
  },

  injectStyles({
    cssLoaderOptions: { sourceMap: true },
    postCSSLoaderOptions: { config: { path: 'webpack' }, sourceMap: true },
    sassLoaderOptions: {
      sassOptions: {
        includePaths: ['node_modules/eswiss/dist'],
      },
      sourceMap: true,
    },
  }),

  loadDevMedia(),

  setupDevServer({
    host: process.env.HOST,
    port: 9489,
  }),

  setupHTML({
    template: 'src/front/template.ejs',
    inject: false,
    templateParameters: {
      app: '',
      css: '',
      desc:
        'The personal website of Matt Lean, a Silicon Valley full-stack web developer and UI/UX designer.',
      keywords: [
        'matt lean',
        'matthew lean',
        'matt',
        'lean',
        'full-stack developer',
        'full-stack',
        'fullstack developer',
        'fullstack',
        'full stack developer',
        'full stack',
        'backend developer',
        'backend',
        'frontend developer',
        'frontend',
        'web developer',
        'developer',
        'web dev',
        'dev',
        'web engineer',
        'software engineer',
        'engineer',
        'development',
        'programmer',
        'programming',
        'user interface designer',
        'ui designer',
        'user experience designer',
        'ux designer',
        'ui/ux designer',
        'ui & ux designer',
        'interface designer',
        'designer',
        'ui',
        'user interface',
        'ux',
        'user experience',
        'web design',
        'design',
        'silicon valley',
        'san francisco bay area',
        'san francisco bay',
        'sf bay area',
        'sf bay',
        'bay area',
        'south bay',
        'northern california',
        'norcal',
        'california',
        'us',
        'usa',
        'united states',
        'united states of america',
        'website',
        'personal',
        'blog',
        'freelance',
        'software',
        'web application',
        'application',
        'web app',
        'webapp',
        'web apps',
        'webapps',
        'websites',
        'web',
        'computer science',
        'graphic design',
        'interactive design',
        'computer',
        'science',
      ],
      js: '/main.js',
      title: 'Matt Lean — Full-Stack Web Developer & UI/UX Designer',
      NODE_ENV: 'development',
    },
  }),
])
