const ROUTE_PREFIX = '/projects/'

const ROUTES = {}
ROUTES[`${ROUTE_PREFIX}sot`] = {
  title: 'Project: Spectral Overlay Tool',
  desc: "Project info for Matt Lean's project: Spectral Overlay Tool",
  keywords: [
    'matt lean',
    'matthew lean',
    'matt',
    'lean',
    'spectral overlay tool',
    'spectral overlay charts',
    'biosearch technologies',
    'lgc',
    'data visualization',
    'data',
    'visualization',
    'charts',
    'graphs',
    'tool',
    'biotechnology',
    'frontend developer',
    'frontend',
    'web developer',
    'developer',
    'web dev',
    'dev',
    'web engineer',
    'software engineer',
    'engineer',
    'development',
    'programmer',
    'programming',
    'user interface designer',
    'ui designer',
    'user experience designer',
    'ux designer',
    'ui/ux designer',
    'ui & ux designer',
    'interface designer',
    'designer',
    'ui',
    'user interface',
    'ux',
    'user experience',
    'web design',
    'design',
    'software',
    'web application',
    'application',
    'web app',
    'webapp',
    'web',
  ],
}
ROUTES[`${ROUTE_PREFIX}ffuh`] = {
  title: 'Project: express-ffuh',
  desc: "Project info for Matt Lean's project: express-ffuh",
  keywords: [
    'matt lean',
    'matthew lean',
    'matt',
    'lean',
    'express-ffuh',
    'express',
    'ffuh',
    'open source',
    'open',
    'source',
    'package',
    'library',
    'backend developer',
    'backend',
    'web developer',
    'developer',
    'web dev',
    'dev',
    'web engineer',
    'software engineer',
    'engineer',
    'development',
    'programmer',
    'programming',
    'software',
    'web',
  ],
}

export default ROUTES
